// Local jobs dataset (60 realistic Indian tech jobs)
// Each job: { id, title, company, location, mode, experience, skills, source, postedDaysAgo, salaryRange, applyUrl, description }
window.JOBS = [
  {
    id: "job-001",
    title: "SDE Intern",
    company: "Infosys",
    location: "Bengaluru, KA",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Data Structures", "Problem Solving"],
    source: "Naukri",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.infosys.com/apply/job-001",
    description: "Join a fast-paced engineering team building backend services.\nWork closely with mentors to learn production-grade coding and testing practices.\nIdeal for recent graduates seeking hands-on experience."
  },
  {
    id: "job-002",
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Chennai, TN",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Spring", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.tcs.com/job-002",
    description: "Participate in a rotational program across engineering teams.\nResponsible for implementing features and fixing production issues.\nStructured mentorship and regular performance reviews."
  },
  {
    id: "job-003",
    title: "Junior Backend Developer",
    company: "Accenture",
    location: "Hyderabad, TG",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "Express", "REST APIs"],
    source: "Indeed",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://accenture.wd3.myworkdayjobs.com/careers/job-003",
    description: "Work on scalable backend services supporting enterprise clients.\nWrite clean, testable code and contribute to deployment pipelines.\nCollaborate with cross-functional teams to deliver requirements."
  },
  {
    id: "job-004",
    title: "Frontend Intern",
    company: "Zoho",
    location: "Chennai, TN",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["HTML", "CSS", "JavaScript", "React"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.zoho.com/apply/job-004",
    description: "Contribute to internal UI components and product pages.\nBuild responsive interfaces and learn component-driven development.\nMentors will guide through real product tasks and reviews."
  },
  {
    id: "job-005",
    title: "QA Intern",
    company: "Freshworks",
    location: "Chennai, TN",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Testing", "Selenium", "Basic SQL"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://freshworks.com/careers/job-005",
    description: "Join QA team to validate product features and automate tests.\nWork with engineers to reproduce issues and improve quality.\nGood opportunity to learn automated testing frameworks."
  },
  {
    id: "job-006",
    title: "Data Analyst Intern",
    company: "Zoho",
    location: "Pune, MH",
    mode: "Remote",
    experience: "Fresher",
    skills: ["SQL", "Excel", "Data Visualization"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://zoho.com/jobs/job-006",
    description: "Support product teams with KPI dashboards and analysis.\nExtract insights from event data and communicate findings clearly.\nIdeal for students with strong analytical curiosity."
  },
  {
    id: "job-007",
    title: "Java Developer (0-1)",
    company: "Wipro",
    location: "Kochi, KL",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "Microservices"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.wipro.com/job-007",
    description: "Implement backend modules for client projects using Java.\nFollow coding standards and participate in code reviews.\nOpportunity to work with cloud-native tooling and CI/CD."
  },
  {
    id: "job-008",
    title: "Python Developer (Fresher)",
    company: "Capgemini",
    location: "Mumbai, MH",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://capgemini.com/careers/job-008",
    description: "Build backend services and integrations using Python.\nWork with senior engineers on design and implementation.\nFocus on code quality and testing for production readiness."
  },
  {
    id: "job-009",
    title: "React Developer (1-3)",
    company: "Cognizant",
    location: "Gurgaon, HR",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "CSS Modules"],
    source: "Indeed",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://jobs.cognizant.com/job-009",
    description: "Deliver user-facing features in a modern React codebase.\nCollaborate with designers to implement accessible UI components.\nContribute to front-end testing and performance improvements."
  },
  {
    id: "job-010",
    title: "SDE Intern",
    company: "Amazon",
    location: "Bengaluru, KA",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Distributed Systems", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://amazon.jobs/job-010",
    description: "Internship on backend services supporting large-scale systems.\nSolve performance and reliability issues under mentor guidance.\nGreat exposure to distributed systems design and monitoring."
  },
  {
    id: "job-011",
    title: "Junior Backend Developer",
    company: "Flipkart",
    location: "Bengaluru, KA",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Kafka", "SQL"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "10–18 LPA",
    applyUrl: "https://flipkartcareers.com/job-011",
    description: "Work on high-throughput order services and inventory systems.\nImplement reliable APIs and participate in incident response.\nCross-team collaboration with product and infrastructure."
  },
  {
    id: "job-012",
    title: "Frontend Intern",
    company: "Swiggy",
    location: "Bengaluru, KA",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["React", "HTML", "CSS"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://careers.swiggy.com/job-012",
    description: "Help build user-facing components for delivery flows.\nWork with engineers to ensure responsive and accessible UI.\nMentoring and real product ownership during the internship."
  },
  {
    id: "job-013",
    title: "QA Intern",
    company: "Razorpay",
    location: "Bengaluru, KA",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Testing", "Postman", "Automation Basics"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://razorpay.com/careers/job-013",
    description: "Join QA efforts for payments platform features.\nCreate reproducible test cases and basic automation scripts.\nLearn how to validate financial flows with high accuracy."
  },
  {
    id: "job-014",
    title: "Data Analyst Intern",
    company: "PhonePe",
    location: "Pune, MH",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SQL", "Python", "Pandas"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://phonepe.com/careers/job-014",
    description: "Support product decisions with quantitative analysis.\nBuild dashboards and run ad-hoc queries for insights.\nExposure to payment product metrics and growth signals."
  },
  {
    id: "job-015",
    title: "Java Developer (0-1)",
    company: "IBM",
    location: "Chennai, TN",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Microservices", "Git"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "3–5 LPA",
    applyUrl: "https://ibm.com/careers/job-015",
    description: "Join an enterprise engineering team building microservices.\nContribute to code, tests, and documentation under mentorship.\nGood introduction to enterprise-grade development workflows."
  },
  {
    id: "job-016",
    title: "Python Developer (Fresher)",
    company: "SAP",
    location: "Bengaluru, KA",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "APIs", "SQL"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "3–5 LPA",
    applyUrl: "https://sap.com/careers/job-016",
    description: "Work on integrations and backend services using Python.\nLearn best practices in code organization and testing.\nCollaborate with senior engineers on feature delivery."
  },
  {
    id: "job-017",
    title: "React Developer (1-3)",
    company: "Paytm",
    location: "Noida, UP",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Redux", "TypeScript"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://paytm.com/careers/job-017",
    description: "Implement complex UI flows for payment experiences.\nOptimize front-end performance and bundle sizes.\nWork closely with UX and backend teams for smooth integrations."
  },
  {
    id: "job-018",
    title: "SDE Intern",
    company: "Zoho",
    location: "Chennai, TN",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["C++", "Algorithms", "Problem Solving"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://zoho.com/careers/job-018",
    description: "Work on algorithmic challenges in product code.\nInterns contribute to feature implementations with mentor help.\nStrong focus on code correctness and efficiency."
  },
  {
    id: "job-019",
    title: "Junior Backend Developer",
    company: "CRED",
    location: "Bengaluru, KA",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Kotlin", "Spring", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://cred.club/careers/job-019",
    description: "Contribute to backend systems for fintech product features.\nWork in small teams and ship high-quality services.\nMentorship from senior engineers and code reviews."
  },
  {
    id: "job-020",
    title: "Frontend Intern",
    company: "Freshworks",
    location: "Chennai, TN",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "Accessibility", "CSS"],
    source: "Indeed",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://freshworks.com/careers/job-020",
    description: "Remote internship building accessible components for product UI.\nWork with design and engineering to ship small features.\nIdeal for interns focused on frontend craftsmanship."
  },
  {
    id: "job-021",
    title: "QA Intern",
    company: "Juspay",
    location: "Bengaluru, KA",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Testing", "APIs", "Automation Basics"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://juspay.com/careers/job-021",
    description: "Help improve reliability of payment gateways by testing scenarios.\nCreate reproducible bug reports and collaborate on fixes.\nGreat learning for those interested in payments infrastructure."
  },
  {
    id: "job-022",
    title: "Data Analyst Intern",
    company: "Zoho",
    location: "Chennai, TN",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Tableau", "Python"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://zoho.com/careers/job-022",
    description: "Work on dashboards that inform product prioritization.\nExtract, clean, and visualize data to answer product questions.\nExposure to large-scale usage metrics and event pipelines."
  },
  {
    id: "job-023",
    title: "Java Developer (0-1)",
    company: "Dell",
    location: "Bengaluru, KA",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "REST"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "3–5 LPA",
    applyUrl: "https://dell.com/careers/job-023",
    description: "Work on backend components for enterprise products.\nLearn design patterns and contribute to production services.\nMentored environment with strong documentation practices."
  },
  {
    id: "job-024",
    title: "Python Developer (Fresher)",
    company: "Oracle",
    location: "Bengaluru, KA",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "APIs", "Cloud Basics"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://oracle.com/careers/job-024",
    description: "Join teams building integrations and automation services in Python.\nWork with cloud services and internal SDKs to deliver features.\nGood opportunity to learn enterprise-grade tooling."
  },
  {
    id: "job-025",
    title: "React Developer (1-3)",
    company: "Swiggy",
    location: "Gurgaon, HR",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Hooks", "Performance"],
    source: "Naukri",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://careers.swiggy.com/job-025",
    description: "Build performant UI experiences for consumer-facing apps.\nOptimize rendering and improve perceived load times.\nCollaborate with designers to refine interactions."
  },
  {
    id: "job-026",
    title: "SDE Intern",
    company: "Razorpay",
    location: "Bengaluru, KA",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Go", "Systems", "Testing"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://razorpay.com/careers/job-026",
    description: "Intern on systems teams working on reliable payment pipelines.\nHands-on experience with production code and observability.\nMentorship and code reviews from experienced engineers."
  },
  {
    id: "job-027",
    title: "Junior Backend Developer",
    company: "CRED",
    location: "Bengaluru, KA",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Java", "SQL", "Microservices"],
    source: "Indeed",
    postedDaysAgo: 9,
    salaryRange: "10–18 LPA",
    applyUrl: "https://cred.club/careers/job-027",
    description: "Work on scoring and transaction services in a fintech environment.\nDevelop APIs, optimize queries, and contribute to reliability.\nStrong mentorship and career learning opportunities."
  },
  {
    id: "job-028",
    title: "Frontend Intern",
    company: "PhonePe",
    location: "Bengaluru, KA",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "CSS", "Testing"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://phonepe.com/careers/job-028",
    description: "Work on components for merchant and consumer flows.\nLearn to write accessible, tested UI code with guidance.\nOpportunity to understand payments UX and edge cases."
  },
  {
    id: "job-029",
    title: "QA Intern",
    company: "Juspay",
    location: "Mumbai, MH",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Testing", "APIs", "Automation Basics"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://juspay.com/careers/job-029",
    description: "Remote QA internship focusing on payments integration testing.\nDevelop test cases and help automate repetitive checks.\nIdeal for those wanting to learn payments QA processes."
  },
  {
    id: "job-030",
    title: "Data Analyst Intern",
    company: "Zoho",
    location: "Bengaluru, KA",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SQL", "Python", "Reporting"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://zoho.com/careers/job-030",
    description: "Support growth and product teams with weekly reports.\nAnalyze user funnels and present clear recommendations.\nPractical exposure to product analytics workflows."
  },
  {
    id: "job-031",
    title: "Java Developer (0-1)",
    company: "Infosys",
    location: "Bengaluru, KA",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "Unit Testing"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.infosys.com/job-031",
    description: "Join an Agile team working on client-facing modules.\nWrite unit-tested code and collaborate closely with QA.\nGood starting point for early-career Java developers."
  },
  {
    id: "job-032",
    title: "Python Developer (Fresher)",
    company: "Accenture",
    location: "Bengaluru, KA",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Flask", "SQL"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "3–5 LPA",
    applyUrl: "https://accenture.wd3.myworkdayjobs.com/careers/job-032",
    description: "Implement services and integrations using Python-based frameworks.\nWork with design docs and mentor guidance to ship features.\nExposure to client projects and enterprise requirements."
  },
  {
    id: "job-033",
    title: "React Developer (1-3)",
    company: "Amazon",
    location: "Hyderabad, TG",
    mode: "Onsite",
    experience: "1-3",
    skills: ["React", "TypeScript", "Testing"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://amazon.jobs/job-033",
    description: "Develop customer-facing user interfaces for large scale apps.\nWork on component libraries and performance tuning.\nCollaborate with backend teams for efficient data flows."
  },
  {
    id: "job-034",
    title: "SDE Intern",
    company: "Flipkart",
    location: "Bengaluru, KA",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Algorithms", "System Design Basics"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://flipkartcareers.com/job-034",
    description: "Intern on core backend teams working on order processing.\nTackle algorithmic problems and participate in design discussions.\nMentorship and a chance to contribute to production services."
  },
  {
    id: "job-035",
    title: "Junior Backend Developer",
    company: "Paytm",
    location: "Noida, UP",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Node.js", "Postgres", "APIs"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "6–10 LPA",
    applyUrl: "https://paytm.com/careers/job-035",
    description: "Work on merchant APIs and payment integrations.\nImprove API reliability and database performance.\nCollaborate with product teams to define requirements."
  },
  {
    id: "job-036",
    title: "Frontend Intern",
    company: "Zoho",
    location: "Chennai, TN",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["JavaScript", "HTML", "CSS"],
    source: "LinkedIn",
    postedDaysAgo: 9,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://zoho.com/careers/job-036",
    description: "Support UI teams in building product pages and widgets.\nLearn component patterns and testing basics with mentor support.\nIdeal for interns wanting production experience."
  },
  {
    id: "job-037",
    title: "QA Intern",
    company: "IBM",
    location: "Pune, MH",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Testing", "Automation Basics", "APIs"],
    source: "Naukri",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://ibm.com/careers/job-037",
    description: "Assist QA teams in automating regression suites and validating features.\nWork closely with developers to ensure quality releases.\nStrong learning opportunity in enterprise QA processes."
  },
  {
    id: "job-038",
    title: "Data Analyst Intern",
    company: "Freshworks",
    location: "Chennai, TN",
    mode: "Remote",
    experience: "Fresher",
    skills: ["SQL", "Excel", "Dashboards"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://freshworks.com/careers/job-038",
    description: "Remote role supporting analytics and reporting needs.\nCreate dashboards and help teams interpret data quickly.\nIdeal for analytical students with good communication skills."
  },
  {
    id: "job-039",
    title: "Java Developer (0-1)",
    company: "Capgemini",
    location: "Mumbai, MH",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "3–5 LPA",
    applyUrl: "https://capgemini.com/careers/job-039",
    description: "Early-career role in client delivery teams.\nWork with senior developers to learn enterprise software practices.\nOpportunity to rotate through different client projects."
  },
  {
    id: "job-040",
    title: "Python Developer (Fresher)",
    company: "Oracle",
    location: "Bengaluru, KA",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Cloud", "APIs"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "3–5 LPA",
    applyUrl: "https://oracle.com/careers/job-040",
    description: "Work on cloud-integrated services and internal tools.\nLearn how to build reliable services with monitoring and tests.\nCollaborative environment with experienced mentors."
  },
  {
    id: "job-041",
    title: "React Developer (1-3)",
    company: "Juspay",
    location: "Bengaluru, KA",
    mode: "Onsite",
    experience: "1-3",
    skills: ["React", "TypeScript", "Integration"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://juspay.com/careers/job-041",
    description: "Build frontend features for payment flows and integrations.\nWork on secure, testable UI components and handle edge cases.\nGood exposure to payments use-cases and reliability concerns."
  },
  {
    id: "job-042",
    title: "SDE Intern",
    company: "Zoho",
    location: "Pune, MH",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["JavaScript", "Node.js", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://zoho.com/careers/job-042",
    description: "Intern with backend teams building APIs and integrations.\nLearn request handling, testing, and deployment basics.\nMentored environment with regular feedback cycles."
  },
  {
    id: "job-043",
    title: "Junior Backend Developer",
    company: "Cognizant",
    location: "Chennai, TN",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "APIs", "SQL"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://jobs.cognizant.com/job-043",
    description: "Support backend features for enterprise clients, working in teams.\nParticipate in code reviews and implement small features.\nStructured onboarding and learning opportunities."
  },
  {
    id: "job-044",
    title: "Frontend Intern",
    company: "Freshworks",
    location: "Chennai, TN",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["React", "CSS", "Testing"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://freshworks.com/careers/job-044",
    description: "Work on product UI improvements and reusable components.\nLearn frontend testing and performance basics with mentor support.\nIdeal for interns who want product exposure."
  },
  {
    id: "job-045",
    title: "QA Intern",
    company: "Amazon",
    location: "Hyderabad, TG",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Testing", "Automation", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://amazon.jobs/job-045",
    description: "Assist QA teams in automation and manual testing for services.\nWork with engineering teams to ensure high-quality releases.\nGreat learning opportunity within high-scale systems."
  },
  {
    id: "job-046",
    title: "Data Analyst Intern",
    company: "Flipkart",
    location: "Bengaluru, KA",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Excel", "Visualization"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://flipkartcareers.com/job-046",
    description: "Support seller and product analytics with dashboards and reports.\nAnalyze trends and present actionable insights to teams.\nOpportunity to understand e-commerce operational metrics."
  },
  {
    id: "job-047",
    title: "Java Developer (0-1)",
    company: "TCS",
    location: "Mumbai, MH",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.tcs.com/job-047",
    description: "Early-career developer working on client projects using Java.\nLearn enterprise practices and follow test-driven development basics.\nStructured mentoring and training programs included."
  },
  {
    id: "job-048",
    title: "Python Developer (Fresher)",
    company: "Capgemini",
    location: "Pune, MH",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "APIs"],
    source: "Indeed",
    postedDaysAgo: 0,
    salaryRange: "3–5 LPA",
    applyUrl: "https://capgemini.com/careers/job-048",
    description: "Work on web services and integrations with Python frameworks.\nParticipate in feature development and testing under guidance.\nGood introduction to software engineering practices."
  },
  {
    id: "job-049",
    title: "React Developer (1-3)",
    company: "Zoho",
    location: "Chennai, TN",
    mode: "Onsite",
    experience: "1-3",
    skills: ["React", "Redux", "TypeScript"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://zoho.com/careers/job-049",
    description: "Develop product UIs and internal component libraries.\nWork on design system alignment and accessibility improvements.\nCollaborate with product teams to deliver polished experiences."
  },
  {
    id: "job-050",
    title: "SDE Intern",
    company: "Cognizant",
    location: "Gurgaon, HR",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Java", "APIs", "Testing"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://jobs.cognizant.com/job-050",
    description: "Remote internship working on backend systems and integrations.\nContribute to code and learn production practices with mentors.\nRemote-friendly role with structured guidance."
  },
  {
    id: "job-051",
    title: "Junior Backend Developer",
    company: "Freshworks",
    location: "Chennai, TN",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Node.js", "Postgres", "APIs"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "6–10 LPA",
    applyUrl: "https://freshworks.com/careers/job-051",
    description: "Build and maintain backend services for SaaS products.\nFocus on robustness, observability, and performance tuning.\nWork with cross-functional teams to deliver customer value."
  },
  {
    id: "job-052",
    title: "Frontend Intern",
    company: "Razorpay",
    location: "Bengaluru, KA",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["React", "CSS", "Testing"],
    source: "LinkedIn",
    postedDaysAgo: 8,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://razorpay.com/careers/job-052",
    description: "Contribute to merchant dashboards and frontend tooling.\nLearn modern frontend workflows and testing approaches.\nHands-on mentorship with product-focused tasks."
  },
  {
    id: "job-053",
    title: "QA Intern",
    company: "PhonePe",
    location: "Pune, MH",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Testing", "Automation Basics", "APIs"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://phonepe.com/careers/job-053",
    description: "Join QA teams testing payment flows and integrations.\nHelp create automation scripts and validate edge cases.\nGood learning path into payments QA and reliability."
  },
  {
    id: "job-054",
    title: "Data Analyst Intern",
    company: "Amazon",
    location: "Hyderabad, TG",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SQL", "Python", "Analysis"],
    source: "Indeed",
    postedDaysAgo: 0,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://amazon.jobs/job-054",
    description: "Support analytics for user behavior and product metrics.\nBuild reports and help influence product decisions with data.\nInternship with strong mentorship and analytical work."
  },
  {
    id: "job-055",
    title: "Java Developer (0-1)",
    company: "IBM",
    location: "Bengaluru, KA",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "Unit Tests"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "3–5 LPA",
    applyUrl: "https://ibm.com/careers/job-055",
    description: "Work in a collaborative team shipping enterprise software.\nImplement features and participate in design and code reviews.\nStrong focus on testing and maintainable code."
  },
  {
    id: "job-056",
    title: "Python Developer (Fresher)",
    company: "SAP",
    location: "Pune, MH",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "APIs", "Data Processing"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "3–5 LPA",
    applyUrl: "https://sap.com/careers/job-056",
    description: "Work on data-processing services and integrations using Python.\nLearn production-ready patterns and collaborate with teams.\nGood entry-level role with mentorship and learning paths."
  },
  {
    id: "job-057",
    title: "React Developer (1-3)",
    company: "Zoho",
    location: "Pune, MH",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Testing", "Accessibility"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://zoho.com/careers/job-057",
    description: "Ship accessible UI components and improve developer ergonomics.\nWork with design systems and product teams to refine UX.\nFocus on long-term maintainability and testing."
  },
  {
    id: "job-058",
    title: "SDE Intern",
    company: "Cognizant",
    location: "Pune, MH",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Java", "APIs", "Testing"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹40k/month Internship",
    applyUrl: "https://jobs.cognizant.com/job-058",
    description: "Remote internship focusing on backend development and testing.\nContribute to code and learn deployment basics with mentors.\nRemote-friendly with structured onboarding."
  },
  {
    id: "job-059",
    title: "Junior Backend Developer",
    company: "Capgemini",
    location: "Mumbai, MH",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Java", "SQL", "Microservices"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "3–5 LPA",
    applyUrl: "https://capgemini.com/careers/job-059",
    description: "Support backend services for enterprise clients and deployments.\nWork with senior engineers to build reliable services and tests.\nExcellent onboarding and training for early-career developers."
  },
  {
    id: "job-060",
    title: "React Developer (1-3)",
    company: "Freshworks",
    location: "Chennai, TN",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "CSS"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://freshworks.com/careers/job-060",
    description: "Implement product UI and contribute to component libraries.\nWork on front-end testing and small feature ownerships.\nCollaborative environment with strong mentorship."
  }
];

